### ISSUE TITLE
Running `ridge_cv` with a pre-defined parcellation yields ValueError

### ISSUE THREAD

**Issue by emdupre** [Parietal-INRIA/fmralign#36]
Running `ridge_cv` with a predefined parcellation such as [the BASC parcellation](https://nilearn.github.io/modules/generated/nilearn.datasets.fetch_atlas_basc_multiscale_2015.html) yields an error:

`
ValueError: Cannot have number of splits n_splits=4 greater than the number of samples: n_samples=1.
`

This seems to be because the [`cv` value for the `RidgeAlignment` estimator is hard-coded at 4](https://github.com/Parietal-INRIA/fmralign/blob/5f3380d94f52652ebb8e643d4bd2b6bad4bc4d32/fmralign/alignment_methods.py#L255). Changing to another value such as `None` for LOO allows `ridge_cv` to run to completion. 

Would it make sense to expose `cv` as an attribute in the user-facing `PairwiseAlignment` class ?

**Comment by thomasbazeille** [comment]
PairwiseAlignment also accepts instances of  estimators in method so here,
you could

*from fmralign.alignment_methods import RidgeAlignment*

*custom_ridge = RidgeAlignment(cv=1)*
*alignment = PairwiseAlignment(method=custom_ridge, ...)*

But still it seems weird to me that clustering on a parcellation changes
anything for Ridge cross-validation, since Ridge should be applied on as
many samples as you have.
Can you provide replication code ? I'd like to have a look.

Le lun. 2 déc. 2019 à 16:38, Elizabeth DuPre <notifications@github.com> a
écrit :

**Comment by emdupre** [comment]
Here's [the code I was trying](https://github.com/neurodatascience/fmralign-tutorials/blob/master/replicate_bazeille_2019.py).

But that's a great idea ! What do you think if I create another example in the documentation that includes that ?

**Comment by thomasbazeille** [comment]
Hello I answered this one in #37 after running your code. The problem here is that you try to fit ridge_cv on only one sample and it's built-in cross validation scheme requires at least one image per fold. 

It's always a bad idea to learn a transform on only one sample because it'll be very noisy. 

+1 for underlining the ability to use a non-default estimator in the docs though, if you have an idea on where it should take place it'd be great.
